version: '3.0'
services:
  nginx_site:
    image: nginx:latest
    container_name: nginx_site
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./site/docker/nginx/:/etc/nginx/conf.d
      - ./site/:/app/site/
      - ./site/docker/nginx/:/var/log/nginx/
    working_dir: /app/site

  nginx_weather_history:
    image: nginx:latest
    container_name: nginx_weather_history
    restart: always
    ports:
      - '8090:8090'
    volumes:
      - ./weather_history/docker/nginx/:/etc/nginx/conf.d
      - ./weather_history/:/app/weather_history/
      - ./weather_history/docker/nginx/:/var/log/nginx/
    working_dir: /app/weather_history

  php_fpm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_fpm
    volumes:
      - ./site/:/app/site/
      - ./weather_history/:/app/weather_history/
    working_dir: /
    restart: always
    ports:
      - '9000:9000'
    links:
      - db

  db:
    image: mariadb
    ports:
      - '3306:3306'
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'weather_history'
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --innodb-flush-log-at-trx-commit=0
      - --innodb-log-file-size=1G
      - --max-allowed-packet=100M
    restart: always
    volumes:
      - ./weather_history/docker/mariadb/data:/var/lib/mysql
      - ./weather_history/docker/mariadb/conf:/etc/mysql/

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8080:8080'